### ISSUE TITLE
On-Boarding

### ISSUE THREAD

**Issue by glueckpress** [glueckpress/Stringintelligenz#12]
Menschen, die das Plugin aktivieren, sollten wir pro-aktiv abholen. Dafür gibt es 2 relevante Szenarien:
### Unterstützte Locale
- Das Plugin wurde aktiviert, die Locale wird unterstützt, es sind also Änderungen im UI sichtbar.
- $user sieht anstelle des üblichen _Plugin aktiviert_ eine Erfolgsnachricht mit kurzen Tipps zu sichtbaren Änderungen, sowie Channels für Feedback und Support.
- Die Notice braucht nicht lokalisierbar zu sein, weil sie eh nur erscheint, wenn das ganze Backend auf Deutsch angezeigt wird.
- Die Notice kann weggeklickt werden und bleibt dann weg.
### Nicht unterstützte Locale (inklusive anderer Locales als Deutsch)
- Das Plugin wurde aktiviert, die Locale wird nicht unterstützt, es sind keine Änderungen im UI sichtbar.
- $user sieht zusätzlich zum üblichen _Plugin aktiviert_ eine Warnung mit Tipps zum Wechseln der Locale im Backend (_Einstellungen→Allgemein_).
- Die Notice ist lokalisierbar; default ist Englisch (wie WP selbst).
- Die Notice kann weggeklickt werden und bleibt dann weg.

**Comment by glueckpress** [comment]
@tfrommen Bist du so nett und machst die Klasse entsprechend fit? :) Ich liefere dann gerne die Inhalte nach.

**Comment by tfrommen** [comment]
@glueckpress und du bist wieder am Zug. :)

Ich habe die Admin-Notice-Klasse konfigurierbar gemacht, und bereits die entsprechenden Templates erstellt. Du musst nun eigentlich nur noch die Datei `templates/admin-notice-plugin-activated.php` entsprechend aufbereiten.

**Comment by glueckpress** [comment]
@tfrommen Merci! Ich glaube, wir haben ein Kodierungsproblem? So kamen deine Commits bei mir an:

![bildschirmfoto 2016-09-25 um 15 06 06](https://cloud.githubusercontent.com/assets/308422/18816915/918ebe12-8353-11e6-8119-6b3c88f379b9.png)

Bei mir waren das [Sonderzeichen und Emoji](https://github.com/glueckpress/Stringintelligenz/commit/c75f71606a8eac0e88729465636f1beac9ff0fc2?diff=split) gewesen.

Ist mir noch nie passiert, dir?

**Comment by tfrommen** [comment]
Hm, nein. Kannst du das wieder geradebiegen?

**Comment by glueckpress** [comment]
Klaro, schon geschehen, kein Ding. ;)

Viel interessanter ist die Sache mit „Notice kann weggeklickt werden und bleibt dann weg“. Hast du zufällig eine schicke Routine rum liegen, die das native `is-dismissible` dafür nutzt?
_(Nach kurzer Googelage: Sowas vielleicht? https://github.com/collizo4sky/persist-admin-notices-dismissal)_

**Comment by tfrommen** [comment]
> Viel interessanter ist die Sache mit „Notice kann weggeklickt werden und bleibt dann weg“. Hast du zufällig eine schicke Routine rum liegen, die das native `is-dismissible` dafür nutzt?

Nein, aber das ist nicht besonders _schwer_. Die Sache ist nur, dass wir dadurch definitiv eine JavaScript-Datei und (wenn man es _richtig_ macht) zwei neue PHP-Dateien einführen. Was natürlich kein Problem ist.

@glueckpress Soll ich mich, bei Zeit, darum kümmern?

**Comment by glueckpress** [comment]
> Soll ich mich, bei Zeit, darum kümmern?

@tfrommen Das wäre klasse, danke dir! Wenn ich es mache, zerhaue ich das schöne OOP. ;)

**Comment by glueckpress** [comment]
Mist, Issue zu taggen vergessen. :/
https://github.com/glueckpress/stringintelligenz/commit/ac8526ac7c791a0fe3cdc5cbcf01b130dc92ade8

**Comment by tfrommen** [comment]
Wassh, ich hab das schon zu 90 % fertig, musste eben aber weg...

**Comment by glueckpress** [comment]
Revert…!!!

**Comment by glueckpress** [comment]
Reverted… https://github.com/glueckpress/stringintelligenz/commit/94f26f7b120c8d68d3aa3b48ea7da337f7d11aad

**Comment by tfrommen** [comment]
@glueckpress here you are.

Ich bin mir nicht sicher, ob das Verhalten so ist, wie du es dir vorgestellt hast, daher schau einfach mal rein...
Falls du ein Notice wieder _reaktivieren_ willst, musst du auf der entsprechenden Site die entsprechende Option `stringintelligenz_admin_notice_SOME-HASH-HERE` löschen.

**Comment by glueckpress** [comment]
@tfrommen Getestet, alles tadellos. 👍  Wollen wir das mergen, oder bist du noch an irgendwas zugange?

**Comment by tfrommen** [comment]
@glueckpress wenn alles funktional deinen Wünschen entpsricht, kann das gemerget werden, klar.
