### ISSUE TITLE
Rollenbezeichnungen abstrakt und nicht stringent

### ISSUE THREAD

**Issue by pixolin** [glueckpress/Stringintelligenz#25]
Die aktuelle Beschreibung der Rollen wirkt auf mich nicht durchgängig und erschwert IMHO das Verständnis, weil zwischen einer abstrakten Rollenbezeichnung (_Mitglied_) und einem abstrakten Ablauf der Beitragserstellung (_Entwürfe_, _Inhalte_, _Redaktion_, _Administration_) gewechselt wird.

Die Originalübersetzung verwendet für die Rollenbezeichnungen _Aufgabenbeschreibungen_ aus dem Zeitungswesen: _Subscriber_, _Contributor_, _Author_, _Editor_ und _Administrator_. Dies drückt vor allem die _Tätigkeiten_ der Beteiligten aus. Als geschlechtsneutrale Übersetzung würde sich deshalb aus meiner Sicht eine substantivierte Tätigkeit besser eignen:

Original | Übersetzung
--------|--------------
Subscriber | Abonnieren
Contributor | Entwerfen
Author | Veröffentlichen
Editor | Herausgeben
Administrator | Administrieren*

(* Die Tätigkeit des Administrators lässt sich zwar auch ohne Verwendung eines Fremdworts mit _Verwalten_ umschreiben, drückt dann aber nicht den Umfang der Berechtigung aus. Der Begriff der Administration hat bei Computerprogrammen eine besondere Bedeutung, die aus der Übersetzung hervorgehen sollte.)

Die substantivierten Tätigkeiten verdeutlichen die Aufgabenverteilung bei der gemeinschaftlichen Arbeit an einem Blog/einer Website ("was darf ich?") und passen gut in den Kontext der Menüs im WordPress Backend ("Standardrolle eines neuen Profils: Abonnieren – Entwerfen – Veröffentlichen – Herausgeben – Administrieren", bzw. "Rolle: …").

**Comment by glueckpress** [comment]
@pixolin Danke für den PR und die ausführliche Beschreibung! Ich hänge mal einen Screenshot an, wie das aussähe:

![screenshot 2016-12-29 um 12 13 27](https://cloud.githubusercontent.com/assets/308422/21542732/4ba5f7dc-cdc0-11e6-9184-88c3007776e4.png)

Ich persönlich finde den Ansatz richtig gedacht, und gleichzeitig habe ich das Gefühl, dass wir an dieser Stelle momentan von der deutschen Übersetzung allein her nicht wirklich entscheidend weiterkommen. Sprich, ich würde das ganze Konzept der _user roles_ und ihrer Benennungen gerne mal mit ein paar Core-Leuten diskutieren, bevor wir hier weitermachen. Also bitte nicht als Desinteresse auffassen, wenn das Issue eine Weile offen bleibt. ;)

**Comment by pixolin** [comment]
Hallo Caspar,

vielen Dank für deine Antwort und den Screenshot, der die Umsetzung tatsächlich schön visualisiert. Bevor die Diskussion wieder ganz von vorne beginnt, möchte ich auf den Thread im Plugin-Forum hinweisen: [Rollenbezeichnungen](https://wordpress.org/support/topic/rollenbezeichnungen/).

**Comment by glueckpress** [comment]
(Geschlossen weil Plugin nicht fortgeführt wird.)
