### ISSUE TITLE
Probleme mit WordPress 4.9.6

### ISSUE THREAD

**Issue by mundschenk-at** [glueckpress/Stringintelligenz#29]
Mir ist aufgefallen, daß neuerdings `Settings` im Backend so stehen bleibt (statt `Einstellungen`). Ob das ganze wirklich erst mit WordPress 4.9.6 aufgetreten ist, kann ich nicht beschwören, aber zumindes bräuchte das Plugin offenbar einmal ein Update.

**Comment by krafit** [comment]
Das liegt daran, dass hier im Plugin alle neuen Strings manuell nachgetragen werden müssen.
Können wir dich da irgendwie unterstützen, @glueckpress?

**Comment by glueckpress** [comment]
@krafit / @mundschenk-at 
Ich möchte leider nicht versprechen, dass ich das Plugin noch weiter pflegen werde. Ich weiss, ich hatte ursprünglich versprochen weiterzumachen, bis das Problem anderweitig gelöst werden kann; aber ehrlich gesagt fällt es mir schwer, mich dazu zu motivieren. 

Stringintelligenz hat laut Plugin-Seite 90+ aktive Installationen. Das Thema an sich wurde von fähigen Leuten (wieder) [aufgegriffen](https://yoav.blog/2017/12/21/gender-fair-wordpress/) und zu einem ersten [Core-Proposal](https://core.trac.wordpress.org/ticket/42725) verarbeitet. Gleichzeitig hat sich bei den deutschsprachigen Polyglots zumindest in Sachen Beidnennung absolut nichts bewegt. 

Letzteres wäre vielleicht sogar noch am ehesten ein Argument, Stringintelligenz weiter/wieder aktuell zu halten. Aber der Aufwand ist echt nicht ohne, und das Interesse mit 90 Installationen anscheinend nicht wirklich vorhanden.

**Comment by mundschenk-at** [comment]
Wirklich weiterzugehen scheint dort allerdings auch nicht so viel (nicht völlig unerwartet bei einem doch für manche kontroversiellen Thema und bei der generellen Behäbigkeit von Core). Was wäre denn konkret bei einer Aktualisierung zu tun (habe mir den Code des Plugins noch nicht näher angesehen)?

BTW: Ich habe hier fünf deutschsprachige Sites in einer Multisite, die zählen gemeinerweise wohl nur als eine Installation.

**Comment by glueckpress** [comment]
Der Code braucht keine Aktualisierung, aber die [drei Sprachdateien](https://github.com/glueckpress/stringintelligenz/tree/master/languages). Um die auf Stand zu bringen, müssen die aktuellen deutschen Core-Übersetzungen gegen die im Plugin bereits vorhandenen gedifft und einzelne Strings ggf. eben anders übersetzt werden. Anschließend muss das Update auf w.org geschoben und die readme.txt auf Englisch und Deutsch aktualisiert werden.

**Comment by glueckpress** [comment]
(Geschlossen, Plugin wird nicht fortgeführt.)
