### ISSUE TITLE
„Zugangsname“ im Kontext „Profil“ durch „Profilname“ ersetzen

### ISSUE THREAD

**Issue by glueckpress** [glueckpress/Stringintelligenz#8]
Im Kontext _Profil_ sollte nicht vom _Zugangsnamen_, sondern vom **Profilnamen** die Rede sein. 
Danke, @pixolin!

**Comment by websupporter** [comment]
Hmmm... Ich verstehe das schon mit dem im Kontext "Profil" bietet sich Profilname an. Aber Zugangsname ist von so schön beschreibender Kraft: Da steh ich vor dem Eingabefeld und soll den Namen eingeben, der mir Zugang verschafft, das ist so :tada: Das wollte ich kurz einwerfen. Aber es holpert natürlich auch und Profilname holpert nicht... Trotzdem: Zugangsname :cry:

**Comment by glueckpress** [comment]
@websupporter Danke, aus ähnlichen Gründen hatte ich noch gezögert und meinen eigenen PR noch nicht gemerged. Wir bräuchten hier mal Feedback von Leuten, die nicht so tief in WP stecken.

**Comment by websupporter** [comment]
Ist das der Grund für "Username or Email Address"?
![username](https://cloud.githubusercontent.com/assets/6458412/19380046/fd0d2670-91fd-11e6-9b65-a7deda67a3ff.jpg)

**Comment by glueckpress** [comment]
@websupporter Nee, eigentlich nicht. Ist das Version von w.org, oder die von hier? Andere Plugins aktiv?

**Comment by websupporter** [comment]
Ah... Sry. WP Version 4.7-alpha-38784. https://core.trac.wordpress.org/changeset/38477

**Comment by StephanieWiermann** [comment]
Meine ersten Testpersonen (2) plädieren für Profilname. Das hieße dann ja auch später im Backend Profil und in FB wäre es auch Profil. Befragung läuft weiter...

**Comment by glueckpress** [comment]
Wir machen das mal mit „Profilname“ in 0.2.0, mal schauen, wie’s ankommt.

**Comment by pixolin** [comment]
Bitte denkt daran, Änderungen auch im Begrüßungstext vorzunehmen.

![Begrüßungstext](http://i.imgur.com/RIzFSjm.png)

🤓
