### ISSUE TITLE
Vereinheitlichung der Groß- und Kleinschreibung der Anrede

### ISSUE THREAD

**Issue by catlauraherzog** [glueckpress/Stringintelligenz#9]
In den Texten gibt es unterschiedliche Schreibweisen der Groß- und Kleinschreibung der Anrede. Beispiel:

Im Hilfe Tab beim Permalink-Setup: "Ein Permalink ist die Webadresse, die zu **Deinem** Inhalt verlinkt." und weiter unten "Auf dieser Seite kannst **du** **deine** gewünschte Permalinkstruktur einstellen."

Wir sollten hier eine Einheitlichkeit einführen. Ich persönlich finde das Kleingeschriebene am angenehmsten zu lesen.

**Comment by glueckpress** [comment]
Danke fürs Aufpassen! Klein ist in der Tat Standard mittlerweile, Groß nur noch Überbleibsel aus der Vergangenheit. Ich mache dazu einen Branch auf, sobald ich wieder am Start bin.
